Branch 명령어 정리 (#13)
MijeongJeon/good_git_study pull request #27
Opened 2019-04-01 13:18 UTC by DayeonJung

2019-04-01 14:38 UTC, MijeongJeon requested changes
다연님! 브랜치 이미지까지 :) 멋집니다.

다만 pull request를 master가 아닌 basic 브랜치로 변경해주세요 :)

2019-04-02 09:05 UTC, DayeonJung commented
오호 제가 마스터로 요청을 했군요! 
저거 수정하려면 pr 취소(?)하고 다시 요청해야 하나요?

2019-04-02 10:56 UTC, MijeongJeon commented
다연님! 다른분들거 머지한 상태라 컨플릭이 발생했습니다! 해결해주세요~ 🤗

2019-04-02 14:27 UTC, MijeongJeon approved these changes

2019-04-02 14:27 UTC, merged