cherry-pick 설명/사용법 추가(#19)
MijeongJeon/good_git_study pull request #28
Opened 2019-04-01 15:39 UTC by KakaoTocs

2019-04-01 15:45 UTC, MijeongJeon requested changes
진우님! 깔끔한 commit message에 체리픽 다양한 사용법까지!! 크윽 좋습니다!

파일 명에 .md 가 빠진것 같아요! 확장자만 지정해서 커밋 올려주세요~ㅎ

2019-04-02 04:55 UTC, KakaoTocs commented
확장자 추가했습니다!

2019-04-02 05:33 UTC, MijeongJeon commented on more_cherry_pick.md
> +`git commit을 선택해서 현재 branch에 반영하기 위한 명령어
맨 앞에 \` 는 `git commit`을 위한것이었나요?

2019-04-02 08:40 UTC, MijeongJeon approved these changes

2019-04-02 08:40 UTC, merged